version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-django-redis-sample
    expose:
      - 8001
    ports:
      - 8001:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    restart: always
    volumes:
      - /Users/fahmi/Documents/Pycharm/django-redis-sample/project/:/usr/src/
    container_name: django-redis-sample
    command: bash -c "python src/manage.py migrate && uwsgi --ini uwsgi.ini"
#    command: bash -c "python src/manage.py runserver 8000"
    ports:
      - 8000:8000
